// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icexfmjpybkkjuwlaqwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZXhmbWpweWJra2p1d2xhcXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjY2MjUsImV4cCI6MjA3MzUwMjYyNX0.eB3POLZknLfVNWI9twDhLhfJE27mTT1lWwMyDmHovms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});